[project]
name = "playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.118.0",
    "pytest>=8.4.2",
    "uvicorn>=0.37.0",
]

[project.scripts]
api = "src.main:start"